---
title: "8_Lab_supervised"
author: "Amar Dani"
date: "2023-07-18"
output: html_document
---

```{r setup}
library(dplyr)
library(reshape2)
library(ggplot2)
library(rsample)
library(parsnip) 
library(ggthemes)
library(MLmetrics)
```

```{r}
fortune_1000 <- read.csv('/Users/sandeep/Downloads/DSRP_2023_AGD/csv_files/Fortune_1000.csv')
#fortune_1000
num_fortune_1000 <- na.omit(select(fortune_1000, revenue:num..of.employees))
#mutate(fortune_1000, )
num_fortune_1000_sectors <- na.omit(select(fortune_1000, revenue:num..of.employees,sector))
big_num_fortune_1000 <- na.omit(select(fortune_1000, revenue:num..of.employees,sector, state))
#num_fortune_1000
#View(fortune_1000)
```

```{r}
pcas <- prcomp(num_fortune_1000, scale. = T)
pcas
summary(pcas)
```
```{r}
pcas_vals <- as.data.frame(pcas$x)
pcas_vals$sector <- num_fortune_1000_sectors$sector
pcas_vals
```
```{r}
reduced_pcas_vals <- filter(pcas_vals, sector == c("Technology","Financials"))
ggplot(reduced_pcas_vals, aes(PC1, PC3, color=sector)) + geom_point() + theme_minimal()
```
```{r}
fortuneAllNumeric <- mutate(big_num_fortune_1000, sector = as.integer(as.factor(sector)), state = as.integer(as.factor(state)))
fortuneAllNumeric
fortuneCors <- cor(fortuneAllNumeric) |> melt() |> as.data.frame()

ggplot(fortuneCors, aes(x = Var1, y = Var2, fill=value)) + geom_tile() + scale_fill_gradient2(low = "red", high ='blue', mid = 'white', midpoint = 0) +
  labs(
    title = 'Tile Map of the Fortune 1000',
    x = 'Variables 1',
    y = 'Variables 2',
    caption = 'Fortune 1000 (2022)'
  ) + 
  theme(
    plot.title = element_text(face = 'bold.italic',size=20),
    axis.title.x = element_text(face = 'bold.italic',size=10),
    axis.title.y = element_text(face = 'bold.italic',size=10),
    plot.caption = element_text(size=8, face='italic',color='grey70', hjust=0)
    #axis.text.x = element_text(angle=90,vjust=0.8,size=10)
  )
```
```{r}
# Regression Dataset Splits

set.seed(71823) # set seed to produce same results

# Classification Dataset Splits
class_split <- initial_split(num_fortune_1000_sectors, prop = .75) 

class_train <- training(class_split) 
class_test <- testing(class_split)
```

```{r}
binary_train_data <- filter(class_train, sector %in% c("Financials", "Technology"))
binary_test_data <- filter(class_test, sector %in% c("Financials", "Technology"))

log_fit <- logistic_reg() |> set_engine("glm") |> set_mode("classification") |> fit(as.factor(sector) ~ revenue + profit + num..of.employees, data = binary_train_data) 

log_fit$fit
summary(log_fit$fit)
```
```{r}
eigenvectors <- (pcas$rotation)^2

evecs <- eigenvectors/sum(eigenvectors)
evecs
```
```{r}
library(Metrics)
library(caret)
fortunePred <- binary_test_data
fortunePred$logReg <- predict(log_fit, binary_test_data)$.pred_class

#fortunePred$sector
#fortunePred$logReg

actual <- factor(fortunePred$sector)
pred <- factor(fortunePred$logReg)

confusionMatrix(pred, actual, mode = "everything", positive = "Financials")


```
```{r}

train_class_data <- training(class_split)
test_class_data <- testing(class_split)

boost_tree_fit <- boost_tree() |> set_engine("xgboost") |> set_mode("classification") |> fit(as.factor(sector) ~ revenue + profit + num..of.employees, data = binary_train_data)

boost_tree_fit$fit
#summary(boost_tree_fit$fit)

fortunePred_f1 <- binary_test_data
fortunePred$boost <- predict(boost_tree_fit, binary_test_data)$.pred_class

#predict(boost_tree_fit, binary_test_data)$.pred_class

actual_f1 <- factor(fortunePred_f1$sector)
pred_f1 <- factor(fortunePred$boost)



pred_f1
actual_f1

confusionMatrix(pred_f1, actual_f1, mode = "everything", positive = "Financials")
```

